FROM apache/airflow:3.1.8

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    duckdb \
    pandas \
    psycopg2-binary \
    python-dotenv \
    requests \
    dbt-postgres==1.9.0